<?php declare(strict_types=1); ?>
<section id="projects-view"<?= $adminPage === 'projects' ? '' : ' hidden' ?>><div class="page-heading"><div><h1>项目管理</h1><p class="muted">注册并保存项目，再前往更新包发布页面上传。</p></div><a class="secondary" href="/?view=releases">前往发布更新包 →</a></div><div class="card files-card"><?php if (isset($_SESSION['release_token_once'])): ?><div class="error-banner"><p>请立即保存此项目令牌，仅显示一次。配置在客户端服务器端，不要放入前端代码或下载 URL。</p><input class="token-display" readonly aria-label="项目访问令牌" value="<?=h($_SESSION['release_token_once'])?>"></div><?php unset($_SESSION['release_token_once']); endif; ?><div class="release-access"><h2>注册项目</h2><form method="post"><?php token(); ?><div class="category-fields"><label>项目标识<input name="release_project" placeholder="例如 myapp" pattern="[a-z][a-z0-9\-]{1,47}" required></label><label>GitHub 仓库<input name="repository" placeholder="owner/repo" required></label></div><p class="muted">标识使用 2–48 位小写字母、数字、连字符，以字母开头。仓库填写 owner/repo。仅支持 stable 正式版本，仓库绑定后不可改；保存后会显示在下方列表，并可在更新包发布页面选择。包名为 项目标识-update.zip。</p><button class="secondary" name="action" value="release_register">保存项目</button></form></div><div class="release-access"><h2>已保存项目与访问令牌</h2><?php foreach ($projectReleases['projects'] as $p): ?><form method="post" class="release-token-form"><?php token(); ?><input type="hidden" name="release_project" value="<?=h($p['id'])?>"><p><strong><?=h($p['id'])?></strong> · <?=h($p['repository'] ?: '尚未绑定 GitHub')?> · <?=empty($p['token_hash']) ? '无访问令牌' : '令牌已配置'?></p><button name="action" value="release_token" class="secondary"><?=empty($p['token_hash']) ? '生成项目令牌' : '轮换项目令牌'?></button><button name="action" value="release_revoke" class="secondary">撤销令牌</button></form><?php endforeach; ?></div><?php if (empty($projectReleases['projects'])): ?><p class="muted">尚未注册项目，请填写项目标识与 GitHub 仓库后点击“保存项目”。</p><?php endif; ?></div></section>
<section id="project-releases" class="card files-card release-panel"<?= $adminPage === 'releases' ? '' : ' hidden' ?>>
<div class="section-heading"><span class="section-icon"><?php icon('upload'); ?></span><div><h2>统一项目更新中心</h2><p class="muted">注册项目 → 上传或拉取 → GitHub 校验 → 手动发布。</p></div><a class="secondary" href="/api">API 对接文档 ↗</a></div>


<?php if (empty($projectReleases['projects'])): ?><p class="error-banner">请先到 <a href="/?view=projects">项目管理</a> 注册并保存项目。</p><?php endif; ?>
<form method="post" enctype="multipart/form-data" class="release-upload"><?php token(); ?><input type="hidden" name="action" value="release_stage"><div class="category-fields"><label>项目<select name="release_project" required><option value="" selected disabled>请选择已保存的项目</option><?php foreach ($projectReleases['projects'] as $p): ?><option value="<?=h($p['id'])?>"><?=h($p['id'])?></option><?php endforeach; ?></select></label><label>更新 ZIP<input name="package" type="file" accept=".zip" required></label><label>update-manifest.json<input name="manifest" type="file" accept=".json" required></label></div><p class="muted">文件需与 GitHub vX.Y.Z 正式 Release 中的资产完全一致。上传只创建草稿，不会立即提供下载。</p><button class="primary">上传并本地校验</button></form>
<details class="release-access"><summary>从 GitHub 拉取更新包</summary><form method="post" class="release-network-form"><?php token(); ?><div class="category-fields"><label>项目<select name="release_project" required><option value="" selected disabled>请选择已保存的项目</option><?php foreach ($projectReleases['projects'] as $p): ?><option value="<?=h($p['id'])?>"><?=h($p['id'])?></option><?php endforeach; ?></select></label><label>目标版本<input name="release_version" placeholder="1.0.0（不带 v）" required></label></div><p class="muted">拉取并校验只生成草稿。大文件或国内连接慢时建议手动上传；命令行入口见 API 文档。香港节点尚未部署。</p><button class="secondary" name="action" value="release_import">拉取并校验</button><span class="release-feedback" role="status" aria-live="polite"></span></form></details>

<div class="table-scroll"><table><thead><tr><th>项目 / 版本</th><th>ZIP 大小</th><th>状态</th><th>更新说明</th><th>操作</th></tr></thead><tbody>
<?php foreach (array_reverse($projectReleases['releases'] ?? [], true) as $release): $p = $projectReleases['projects'][$release['project']] ?? []; ?>
<tr><td><?=h($release['project'])?> / v<?=h($release['version'])?></td><td><?=h(bytesLabel($release['size']))?></td><td><?= $release['status'] === 'draft' ? (empty($release['github']) ? '待 GitHub 校验' : '来源已校验，待发布') : (($p['latest'] ?? '') === $release['id'] ? '当前已发布' : '历史已发布') ?><?php if (!empty($release['github'])): ?><small>校验于 <?=h($release['github']['checked_at'])?></small><?php endif; ?></td><td class="release-notes"><?=h($release['notes'])?></td><td><?php if ($release['status'] === 'draft'): ?><form method="post" class="release-network-form"><?php token(); ?><input type="hidden" name="release_id" value="<?=h($release['id'])?>"><button class="secondary" name="action" value="release_verify">校验 GitHub</button><button class="primary" name="action" value="release_publish"<?= empty($p['token_hash']) || empty($release['github']) ? ' disabled' : '' ?>>发布</button><span class="release-feedback" role="status" aria-live="polite"></span></form><?php else: ?><?=empty($release['github']) ? '旧版本地发布（兼容保留）' : '已发布'?><?php endif; ?></td></tr>
<?php endforeach; ?></tbody></table></div>
<?php if (empty($projectReleases['releases'])): ?><p class="muted">尚无更新包。上传未完成或校验失败的文件不会出现在更新查询 API 中。</p><?php endif; ?>
</section>
