<?php declare(strict_types=1); ?>
<section id="projects-view"<?= $adminPage === 'projects' ? '' : ' hidden' ?>><div class="page-heading"><div><h1>项目管理</h1><p class="muted">注册并保存项目，再前往更新包发布页面上传。</p></div><a class="secondary" href="/?view=releases">前往发布更新包 →</a></div><div class="card files-card"><?php if (isset($_SESSION['release_token_once'])): ?><div class="error-banner"><p>请立即保存此项目令牌，仅显示一次。配置在客户端服务器端，不要放入前端代码或下载 URL。</p><input class="token-display" readonly aria-label="项目访问令牌" value="<?=h($_SESSION['release_token_once'])?>"></div><?php unset($_SESSION['release_token_once']); endif; ?><div class="release-access"><h2>注册项目</h2><form method="post"><?php token(); ?><div class="category-fields"><label>项目标识<input name="release_project" placeholder="例如 myapp" pattern="[a-z][a-z0-9\-]{1,47}" required></label><label>GitHub 仓库<input name="repository" placeholder="owner/repo" required></label></div><p class="muted">标识使用 2–48 位小写字母、数字、连字符，以字母开头。仓库填写 owner/repo。仅支持 stable 正式版本，仓库绑定后不可改；保存后会显示在下方列表，并可在更新包发布页面选择。包名为 项目标识-update.zip。</p><button class="secondary" name="action" value="release_register">保存项目</button></form></div><div class="release-access"><h2>已保存项目与访问令牌</h2><?php foreach ($projectReleases['projects'] as $p): ?><form method="post" class="release-token-form"><?php token(); ?><input type="hidden" name="release_project" value="<?=h($p['id'])?>"><p><strong><?=h($p['id'])?></strong> · <?=h($p['repository'] ?: '尚未绑定 GitHub')?> · <?=empty($p['token_hash']) ? '无访问令牌' : '令牌已配置'?></p><button name="action" value="release_token" class="secondary"><?=empty($p['token_hash']) ? '生成项目令牌' : '轮换项目令牌'?></button><button name="action" value="release_revoke" class="secondary">撤销令牌</button></form><?php endforeach; ?></div><?php if (empty($projectReleases['projects'])): ?><p class="muted">尚未注册项目，请填写项目标识与 GitHub 仓库后点击“保存项目”。</p><?php endif; ?></div></section>
<section id="project-releases" class="card files-card release-panel"<?= $adminPage === 'releases' ? '' : ' hidden' ?>>
<div class="section-heading"><span class="section-icon"><?php icon('upload'); ?></span><div><h2>统一项目更新中心</h2><p class="muted">注册项目 → 上传或拉取 → GitHub 校验 → 手动发布。</p></div><a class="secondary" href="/api" target="_blank" rel="noopener noreferrer">API 对接文档 ↗</a></div>


<?php if (empty($projectReleases['projects'])): ?><p class="error-banner">请先到 <a href="/?view=projects">项目管理</a> 注册并保存项目。</p><?php endif; ?>
<form method="post" enctype="multipart/form-data" class="release-upload" id="release-upload"><?php token(); ?><input type="hidden" name="action" value="release_stage"><div class="category-fields"><label>项目<select name="release_project" required><option value="" selected disabled>请选择已保存的项目</option><?php foreach ($projectReleases['projects'] as $p): ?><option value="<?=h($p['id'])?>"><?=h($p['id'])?></option><?php endforeach; ?></select></label><label>更新 ZIP<input name="package" type="file" accept=".zip" required></label><label>update-manifest.json<input name="manifest" type="file" accept=".json" required></label></div><p class="muted">文件需与 GitHub vX.Y.Z 正式 Release 中的资产完全一致。上传只创建草稿，不会立即提供下载。</p><button class="primary" id="release-upload-button">上传并本地校验</button></form>
<div id="release-upload-feedback" class="release-upload-feedback" hidden><progress id="release-upload-progress" max="100" value="0" aria-label="更新包上传进度"></progress><p id="release-upload-status" role="status" aria-live="polite"></p><a href="/?view=releases">刷新发布记录，确认上传结果</a></div>
<details class="release-access"><summary>从 GitHub 拉取更新包</summary><form method="post" class="release-network-form"><?php token(); ?><div class="category-fields"><label>项目<select name="release_project" required><option value="" selected disabled>请选择已保存的项目</option><?php foreach ($projectReleases['projects'] as $p): ?><option value="<?=h($p['id'])?>"><?=h($p['id'])?></option><?php endforeach; ?></select></label><label>目标版本<input name="release_version" placeholder="1.0.0（不带 v）" required></label></div><p class="muted">拉取并校验只生成草稿。大文件或国内连接慢时建议手动上传；命令行入口见 API 文档。香港节点尚未部署。</p><button class="secondary" name="action" value="release_import">拉取并校验</button><span class="release-feedback" role="status" aria-live="polite"></span></form></details>

<?php require __DIR__ . '/release-list.php'; ?>
<?php if (empty($projectReleases['releases'])): ?><p class="muted">尚无更新包。上传未完成或校验失败的文件不会出现在更新查询 API 中。</p><?php endif; ?>
</section>
